version: '3'

services:
  postgres:
    container_name: database
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345678x@X
      PGDATA: /data/postgres
    volumes:
      - $PWD/pg:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
  mysql-keycloak:
    container_name: keycloak-database
    image: mysql:5.7
    volumes:
      - mysql_keycloak_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    restart: unless-stopped

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:16.1.0
    command: -b 0.0.0.0 -Dkeycloak.profile=preview
    restart: on-failure
    environment:
      PROXY_ADDRESS_FORWARDING: "true"
      DB_VENDOR: MYSQL
      DB_ADDR: mysql-keycloak
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: 12345678x@X
      REDIRECT_SOCKET: "proxy-https"
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "connectTimeout=30000"
    ports:
      - "9090:8080"
    depends_on:
      - mysql-keycloak

volumes:
  mysql_data:
    driver: local
  mysql_keycloak_data:
    driver: local
