http:
  host: 'localhost'
  port: 5000

https:
  host: 'localhost'
  port: 5001

db:
  keycloak:
    url: '34.142.193.100'
    port: 3307
    database: 'keycloak'
    username: 'root'
    password: 'root'
    synchronize: false
  mysql:
    url: '34.142.193.100'
    port: 3306
    database: 'db'
    username: 'root'
    password: '12345678x@X'
    synchronize: false
  postgres:
    url: '34.142.193.100'
    port: 5432
    database: 'postgres'
    username: 'admin'
    password: '12345678x@X'
    synchronize: false

keycloak:
  host: '34.142.193.100'
  port: 9090
  client:
    realm: 'authentication'
    id: 'authentication-api'
    secret: 'eAaFWFGhQbwR02U4g7M9xsd9BryRaeJ7'
  master_username: 'admin'
  master_password: '12345678x@X'
  grant_type:
    token_exchange: 'urn:ietf:params:oauth:grant-type:token-exchange'
    refresh_token: 'urn:ietf:params:oauth:token-type:refresh_token'
    native_refresh_token: 'refresh_token'
    password: 'password'

redis:
  host: '34.142.193.100'
  port: 6379
  username:
  password:

elasticsearch:
  host: '34.142.193.100'
  port: 9200
  username: 'elastic'
  password: 'admin'

firebase:
  apiKey: "AIzaSyBu0hVHThHGd5OQLxQWnNZLSgdLGiYsfZE"
  authDomain: "fptu-library-booking.firebaseapp.com"
  projectId: "fptu-library-booking"
  storageBucket: "fptu-library-booking.appspot.com"
  messagingSenderId: "1013204251190"
  appId: "1:1013204251190:web:52aeef762a7eb980e51e97"
  measurementId: "G-MQLQ866QXQ"
  oauth:
    clientId: "fptu-library-booking"
    audience:
      - "fptu-library-booking"
      - "1013204251190-74m7mtno9e3ge4fdie3422hotor5217c.apps.googleusercontent.com"
      - "fptu-library-booking.firebaseapp.com"
      - "1013204251190-nkd63gan2a17tj8lffmh83jl6scco9g6.apps.googleusercontent.com"

cloudinary:
  name: "dryel0zfz"
  apiKey: "376422144959338"
  apiSecret: "9BC06IO522Z_99FHKsAqfh1K3xo"
  secure: true
