version: '3'

services:
  mysql:
    container_name: database
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    ports:
      - "3306:3306"
  mysql-keycloak:
    container_name: keycloak-database
    image: mysql:5.7
    volumes:
      - mysql_keycloak_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
  redis:
    container_name: redis_cache
    image: "redis:alpine"
    command: redis-server --requirepass 12345678x@X
    ports:
      - "6380:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
  phpmyadmin:
    container_name: phpmyadmin-lms
    image: phpmyadmin
    ports:
      - "8090:80"
    environment:
      PMA_HOST: mysql
  phpmyadmin-keycloak:
    image: phpmyadmin
    ports:
      - "4444:80"
    environment:
      - PMA_ARBITRARY=1
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:16.1.0
    command: -b 0.0.0.0
    environment:
      PROXY_ADDRESS_FORWARDING: true
      DB_VENDOR: MYSQL
      DB_ADDR: mysql-keycloak
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "connectTimeout=30000"
    ports:
      - "9090:8080"
    depends_on:
      - mysql-keycloak

volumes:
  data01:
    driver: local
  mysql_data:
    driver: local
  mysql_keycloak_data:
    driver: local
