require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/@nrwl/react-native/nx_post_install'

platform :ios, '11.0'

target 'Mobile' do
  config = use_native_modules!
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'
  pod 'react-native-config', :path => '../node_modules/react-native-config'
  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'
  pod 'RNGoogleSignin', :path => '../node_modules/@react-native-google-signin/google-signin'
  pod 'RNCPicker', :path => '../node_modules/@react-native-picker/picker'
  pod 'react-native-mmkv', :path => '../node_modules/react-native-mmkv'
  pod 'react-native-date-picker', :path => '../node_modules/react-native-date-picker'
  pod 'react-native-camera', :path => '../node_modules/react-native-camera'
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
  pod 'RNSVG', :path => '../node_modules/react-native-svg'
  pod 'RNScreens', :path => '../node_modules/react-native-screens'
  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-async-storage/async-storage'
  pod 'RNFBAuth', :path => '../node_modules/@react-native-firebase/auth'

  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-FaceID', :path => "#{permissions_path}/FaceID"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly"

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    nx_post_install(installer)
  end
end
